# Generated by Django 5.0.4 on 2026-04-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_seriesplan_razorpayorder_plan'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='razorpayorder',
            new_name='payments_ra_user_id_33ac22_idx',
            old_name='payments_rz_user_series_status_idx',
        ),
        migrations.RenameIndex(
            model_name='razorpayorder',
            new_name='payments_ra_razorpa_fb3168_idx',
            old_name='payments_rz_order_id_idx',
        ),
        migrations.RenameIndex(
            model_name='seriesaccess',
            new_name='payments_se_user_id_fdc5c7_idx',
            old_name='payments_se_user_id_series_active_idx',
        ),
        migrations.RenameIndex(
            model_name='seriesaccess',
            new_name='payments_se_series__140724_idx',
            old_name='payments_se_series_active_idx',
        ),
    ]
