# Generated by Django 5.0.4 on 2026-01-27 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testseries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Supports LaTeX markup in text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/images/')),
                ('is_math', models.BooleanField(default=False, help_text='If true, render text as LaTeX')),
                ('explanation', models.TextField(blank=True)),
                ('marks_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('negative_marks_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testseries.section')),
            ],
            options={
                'ordering': ['section', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/options/')),
                ('is_math', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question')),
            ],
            options={
                'ordering': ['question', 'order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['section'], name='questions_q_section_fd3b22_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='questions_q_is_acti_723019_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='questions_q_created_d1d888_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['question', 'is_correct'], name='questions_o_questio_7fc9c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='uq_option_order_within_question'),
        ),
    ]
