# Generated by Django 5.0.4 on 2026-01-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Text extracted from image via OCR. Admin can edit this.', null=True),
        ),
    ]
