# Generated by Django 5.0.4 on 2026-01-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution_image',
            field=models.ImageField(blank=True, help_text='Solution diagram or working steps image', null=True, upload_to='questions/solutions/'),
        ),
    ]
