# Generated by Django 5.0.4 on 2026-02-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_solution_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, help_text='Question text - Supports LaTeX markup (optional if image provided)'),
        ),
    ]
