# Generated by Django 5.0.4 on 2026-04-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='draft_option_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='draft_question_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
