# Generated by Django 5.0.4 on 2026-04-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_option_draft_option_id_question_draft_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_bonus',
            field=models.BooleanField(default=False, help_text='If True, all students get full marks regardless of their answer'),
        ),
    ]
