# Generated by Django 5.0.4 on 2026-04-20 11:18

from django.db import migrations, models


def backfill_correct_option_ids(apps, schema_editor):
    """Populate correct_option_ids for every existing published question."""
    Question = apps.get_model('questions', 'Question')
    Option = apps.get_model('questions', 'Option')

    # Build question_id → [correct_option_id, ...] map in 1 query
    correct_opts = Option.objects.filter(is_correct=True).values('question_id', 'id')
    correct_by_q = {}
    for row in correct_opts:
        correct_by_q.setdefault(row['question_id'], []).append(row['id'])

    batch = []
    for q in Question.objects.all():
        q.correct_option_ids = correct_by_q.get(q.id, [])
        batch.append(q)
        if len(batch) == 500:
            Question.objects.bulk_update(batch, ['correct_option_ids'])
            batch.clear()
    if batch:
        Question.objects.bulk_update(batch, ['correct_option_ids'])


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_is_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_option_ids',
            field=models.JSONField(blank=True, default=list, help_text='Auto-populated on publish. Do not edit manually.'),
        ),
        migrations.RunPython(backfill_correct_option_ids, migrations.RunPython.noop),
    ]
