# Generated by Django 5.0.4 on 2026-04-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_correct_option_ids'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='questions_q_section_fd3b22_idx',
        ),
    ]
