# Generated by Django 5.0.4 on 2026-01-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdraft',
            name='published_test_id',
            field=models.IntegerField(blank=True, help_text='ID of published test', null=True),
        ),
    ]
