# Generated by Django 5.0.4 on 2026-01-29 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_builder', '0002_testdraft_published_test_id'),
        ('testseries', '0002_alter_testseries_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='testdraft',
            constraint=models.UniqueConstraint(fields=('series', 'name', 'created_by'), name='unique_test_draft_per_user_series'),
        ),
    ]
