# Generated by Django 5.0.4 on 2026-02-03 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_builder', '0003_testdraft_unique_test_draft_per_user_series'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testdraft',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When the lock was acquired', null=True),
        ),
        migrations.AddField(
            model_name='testdraft',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='Admin currently editing this draft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_drafts', to=settings.AUTH_USER_MODEL),
        ),
    ]
