# Generated by Django 5.0.4 on 2026-02-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_builder', '0005_draft_series_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiondraft',
            name='time_limit_minutes',
            field=models.IntegerField(default=0, help_text='Time limit for this section in minutes (only used if use_sectional_timing is True)'),
        ),
        migrations.AddField(
            model_name='testdraft',
            name='use_sectional_timing',
            field=models.BooleanField(default=False, help_text='If True, each section has its own time limit and auto-advances when time ends'),
        ),
    ]
