# Generated by Django 5.0.4 on 2026-02-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_builder', '0006_sectiondraft_time_limit_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiondraft',
            name='option_text',
            field=models.CharField(blank=True, help_text='Option text (optional if image provided)', max_length=500),
        ),
        migrations.AlterField(
            model_name='questiondraft',
            name='question_text',
            field=models.TextField(blank=True, help_text='Question text (optional if image provided)'),
        ),
    ]
