# Generated by Django 5.0.4 on 2026-04-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_builder', '0009_testdraft_shuffle_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondraft',
            name='is_bonus',
            field=models.BooleanField(default=False, help_text='If True, all students get full marks for this question regardless of their answer'),
        ),
    ]
