# Generated by Django 5.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_builder', '0010_questiondraft_is_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdraft',
            name='continuous_numbering',
            field=models.BooleanField(
                default=False,
                help_text='If True, question numbers continue across sections (1, 2, …, N) instead of resetting to 1 per section',
            ),
        ),
    ]
