# Generated by Django 5.0.4 on 2026-04-21 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_builder', '0011_testdraft_continuous_numbering'),
        ('testseries', '0013_remove_section_testseries__test_id_b6db3d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pdfimportjob',
            index=models.Index(fields=['status', 'created_at'], name='test_builde_status_9f557a_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfimportjob',
            index=models.Index(fields=['draft', 'status'], name='test_builde_draft_i_4810dc_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfimportjob',
            index=models.Index(fields=['section', 'status'], name='test_builde_section_82e67d_idx'),
        ),
        migrations.AddIndex(
            model_name='testdraft',
            index=models.Index(fields=['created_by', 'is_published'], name='test_builde_created_a9a390_idx'),
        ),
        migrations.AddIndex(
            model_name='testdraft',
            index=models.Index(fields=['locked_by', 'locked_at'], name='test_builde_locked__2ef6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='testdraft',
            index=models.Index(fields=['created_at'], name='test_builde_created_f9cc59_idx'),
        ),
    ]
