# Generated by Django 5.0.4 on 2026-03-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
