# Generated by Django 5.0.4 on 2026-03-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_active_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, help_text='Enter 10 digit mobile number', max_length=15),
        ),
    ]
