# Generated by Django 5.0.4 on 2026-04-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_forgotpasswordrequest'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='forgotpasswordrequest',
            index=models.Index(fields=['status', 'created_at'], name='accounts_fo_status_4944b4_idx'),
        ),
        migrations.AddIndex(
            model_name='forgotpasswordrequest',
            index=models.Index(fields=['user', 'status'], name='accounts_fo_user_id_6fbd99_idx'),
        ),
    ]
