# Generated by Django 5.0.4 on 2026-01-27 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='testseries__slug_eec2d9_idx'), models.Index(fields=['is_active'], name='testseries__is_acti_443a8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='0 means unlimited')),
                ('marks_per_question', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('negative_marks_per_question', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='testseries.testseries')),
            ],
            options={
                'ordering': ['series', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('time_limit_seconds', models.PositiveIntegerField(default=0, help_text='0 means no separate limit')),
                ('marks_per_question', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('negative_marks_per_question', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='testseries.test')),
            ],
            options={
                'ordering': ['test', 'order', 'name'],
                'indexes': [models.Index(fields=['test'], name='testseries__test_id_b6db3d_idx'), models.Index(fields=['is_active'], name='testseries__is_acti_51dd95_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('test', 'name'), name='uq_section_name_within_test'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('test', 'order'), name='uq_section_order_within_test'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['series'], name='testseries__series__43a705_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['is_active'], name='testseries__is_acti_6fa604_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['starts_at'], name='testseries__starts__c0ae9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(fields=('series', 'slug'), name='uq_test_slug_within_series'),
        ),
    ]
