# Generated by Django 5.0.4 on 2026-01-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testseries',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
