# Generated by Django 5.0.4 on 2026-02-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0003_series_sections_and_test_links'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='seriessection',
            index=models.Index(fields=['series'], name='testseries__series__d58b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='seriessection',
            index=models.Index(fields=['is_active'], name='testseries__is_acti_d31f97_idx'),
        ),
        migrations.AddIndex(
            model_name='seriessubsection',
            index=models.Index(fields=['section'], name='testseries__section_a812b6_idx'),
        ),
        migrations.AddIndex(
            model_name='seriessubsection',
            index=models.Index(fields=['is_active'], name='testseries__is_acti_3f4e1b_idx'),
        ),
    ]
