# Generated by Django 5.0.4 on 2026-02-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0004_seriessection_testseries__series__d58b4e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='use_sectional_timing',
            field=models.BooleanField(default=False, help_text='If True, each section has its own time limit and auto-advances when time ends'),
        ),
    ]
