# Generated by Django 5.0.4 on 2026-02-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0006_testseries_exam_sections'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='testseriesexamsection',
            new_name='testseries__series__fda1fe_idx',
            old_name='testseries_series_i_8b5a7f_idx',
        ),
    ]
