# Generated by Django 5.0.4 on 2026-02-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0007_rename_testseries_series_i_8b5a7f_idx_testseries__series__fda1fe_idx'),
        ('testseries', '0007_testseries_highlights'),
    ]

    operations = [
    ]
