# Generated by Django 5.0.4 on 2026-02-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0008_merge_20260214_1855'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='testserieshighlight',
            new_name='testseries__series__2f22e5_idx',
            old_name='testseries_series_i_9a5a3f_idx',
        ),
    ]
