# Generated by Django 5.0.4 on 2026-04-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0010_test_shuffle_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='draft_section_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
