# Generated by Django 5.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0011_section_draft_section_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='continuous_numbering',
            field=models.BooleanField(
                default=False,
                help_text='If True, question numbers continue across sections (1, 2, …, N) instead of resetting to 1 per section',
            ),
        ),
    ]
