# Generated by Django 5.0.4 on 2026-04-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0012_test_continuous_numbering'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='section',
            name='testseries__test_id_b6db3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='test',
            name='testseries__series__43a705_idx',
        ),
    ]
