set $redirect_https 0;

if ($http_x_forwarded_proto = "http") {
    set $redirect_https 1;
}

if ($request_uri ~ "^/health/?$") {
    set $redirect_https 0;
}

if ($redirect_https = 1) {
    return 301 https://$host$request_uri;
}