# Generated by Django 5.0.4 on 2026-01-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('not_visited', 'Not Visited'), ('visited', 'Visited'), ('answered', 'Answered'), ('marked_for_review', 'Marked for Review'), ('answered_and_marked', 'Answered & Marked')], default='not_visited', max_length=25),
        ),
    ]
