# Generated by Django 5.0.4 on 2026-03-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_answer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='time_remaining_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
