# Generated by Django 5.0.4 on 2026-03-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0004_testattempt_question_order_option_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='option_order',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='question_order',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
