# Generated by Django 5.0.4 on 2026-04-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0007_backfill_attempt_section_timings'),
        ('testseries', '0013_remove_section_testseries__test_id_b6db3d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='answer',
            name='attempts_an_attempt_908db2_idx',
        ),
        migrations.RemoveIndex(
            model_name='attemptsectiontiming',
            name='attempts_att_attempt_970021_idx',
        ),
        migrations.RemoveIndex(
            model_name='attemptsectiontiming',
            name='attempts_att_section_ab6b6a_idx',
        ),
        migrations.RemoveIndex(
            model_name='testattempt',
            name='attempts_te_user_id_9d9721_idx',
        ),
        migrations.RemoveIndex(
            model_name='testattempt',
            name='attempts_te_test_id_f34afb_idx',
        ),
        migrations.RenameIndex(
            model_name='testattempt',
            new_name='attempts_te_test_id_99a22e_idx',
            old_name='attempts_tes_test_id_047d5b_idx',
        ),
        migrations.RenameIndex(
            model_name='testattempt',
            new_name='attempts_te_status_029508_idx',
            old_name='attempts_tes_status_a9eebf_idx',
        ),
        migrations.RenameIndex(
            model_name='testattempt',
            new_name='attempts_te_evaluat_fe645c_idx',
            old_name='attempts_tes_evaluat_a20d2f_idx',
        ),
        migrations.AddIndex(
            model_name='attemptsectiontiming',
            index=models.Index(fields=['attempt', 'section'], name='attempts_at_attempt_e268bb_idx'),
        ),
    ]
